### ISSUE TITLE
hub.tools.conf.integrate doesn't take list as 1st arg

### ISSUE THREAD

**Issue by smokeytheblair** [saltstack/pop#34]
**Expected**:
hub.tools.conf.integrate(['poppy'], loader='yaml', roots=True)

**Actual**:
hub.tools.conf.integrate('poppy', loader='yaml', roots=True)

The `integrate` call does not throw or traceback.  It simply fails to load the config.

**Comment by thatch45** [comment]
I can't reproduce this and the code is in place to handle it so I am going to close it out
