### ISSUE TITLE
sys.path length explosion

### ISSUE THREAD

**Issue by dhiltonp** [saltstack/pop#60]
Using heist at d885ede, run `time pytest tests/unit/heist`.

Time between each test increases exponentially. Apparently sys.path is growing exponentially.

https://github.com/saltstack/pop/blob/master/pop/dirs.py#L45 

On the first time through `dynamic_dirs`, an extra dir is added to `sys.path`. On the second time, 2 extra dirs. On the 3rd time 4 extra dirs etc.

By some time in the 11th test, `/home/dhiltonp/code/heist` appears 3951 times in sys.path.

**Comment by thatch45** [comment]
oh, that should be easy to fix

**Comment by dhiltonp** [comment]
I've got a fix, but not a regression test

**Comment by thatch45** [comment]
awesome!

**Comment by thatch45** [comment]
Just to make sure this is documented here. The fix is in 7.5, but we still need a regression test

**Comment by dhiltonp** [comment]
See #62
