### ISSUE TITLE
Place To Discuss and Learn

### ISSUE THREAD

**Issue by kwrobert** [saltstack/pop#68]
Hello wonderful pop developers!

I heard about this project on [one of my favorite podcasts](https://www.pythonpodcast.com/plugin-oriented-programming-episode-240/), and was immediately very excited to try it out on one of my new projects. 

As I'm working through this new, exciting programming paradigm, it would be awesome if I could discuss ideas, ask questions, share new patterns, etc. with the community. Is there a central place to get together and communicate? Are Github issues sufficient? 

Thanks!

**Comment by thatch45** [comment]
hi @kwrobert ! Great to hear from you, things are very young, the best place right now is on the saltstack slack:
https://saltstackcommunity.herokuapp.com/

Sorry, I am a little slow on the replies, I have been on the road a lot.
